/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.dao.Perfumes;
import javax.swing.JOptionPane;


/**
 *
 * @author s.lucas
 */
public class frmSistema extends javax.swing.JFrame {

    /**
     * Creates new form frmSistema
     */
    public frmSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lbTituloSistema = new javax.swing.JLabel();
        lbPerfume = new javax.swing.JLabel();
        txtPerfume = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        abtnOrdenar = new javax.swing.JToggleButton();
        lbPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloSistema.setFont(new java.awt.Font("Schadow BT", 1, 18)); // NOI18N
        lbTituloSistema.setText("Lista de Perfumes");
        jPanel1.add(lbTituloSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        lbPerfume.setText("Perfume:");
        jPanel1.add(lbPerfume, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, -1, -1));

        txtPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerfumeActionPerformed(evt);
            }
        });
        jPanel1.add(txtPerfume, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 34, 320, -1));

        txtLista.setColumns(20);
        txtLista.setRows(5);
        jScrollPane1.setViewportView(txtLista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 425, 234));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/icons/save.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/icons/trash.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/icons/edit.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/icons/list.png"))); // NOI18N
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        abtnOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/icons/sort_down.png"))); // NOI18N
        abtnOrdenar.setRolloverEnabled(false);
        abtnOrdenar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/icons/sort_up.png"))); // NOI18N
        abtnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(abtnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        lbPesquisa.setText("Pesquisar:");
        jPanel1.add(lbPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        jPanel1.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 310, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/icons/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/icons/clear.png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Perfumes item = new Perfumes();
    private void txtPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerfumeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        item.pesquisar(txtPesquisa.getText());
        txtPesquisa.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtPerfume.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o nome do perfume no campo ao lado: ");
        } else {
            item.salvar(txtPerfume.getText());
            txtPerfume.setText(null);
            txtPerfume.requestFocus();            
            txtLista.setText(item.listar());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        txtLista.setText(item.listar());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        item.excluir(Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o código do item que deseja excluir: ")));
        txtLista.requestFocus();
        txtLista.setText(item.listar());
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtLista.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void abtnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtnOrdenarActionPerformed
        if (abtnOrdenar.isSelected() == true) {
            item.ordenarAsc();
            txtLista.setText(item.listar());
        } else {
            item.ordenarDesc();
            txtLista.setText(item.listar());
        }
    }//GEN-LAST:event_abtnOrdenarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        item.editar(Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o código do item que deseja editar: ")), JOptionPane.showInputDialog(null, "Digite o nome do novo item: "));
        txtLista.setText(item.listar());
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton abtnOrdenar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPerfume;
    private javax.swing.JLabel lbPesquisa;
    private javax.swing.JLabel lbTituloSistema;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtPerfume;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
